changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Documentations
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
