name: Publish
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          scope: "@zzzkan"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Publish package to npmjs
        run: yarn publish --access public
        working-directory: ./site
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
